//! Lexicon plane classification for GAIA-2.0 document chunks.
//!
//! Two parallel dictionaries — Order and Chaos — must never be silently conflated.
//! Every `DocumentChunk` emitted by the chunker carries a `LexiconPlane` tag so
//! the RAG pipeline always knows which plane it is pulling from.
//!
//! ## Classification pipeline
//!
//! 1. The chunker sets `lexicon_plane = Bridge` (safe default, C30).
//! 2. The ingestion pipeline calls `classify_document_chunk(&mut chunk)` once
//!    per chunk immediately after chunking.
//! 3. `classify_document_chunk` builds a `LexiconSignals` struct from the
//!    chunk's existing fields (no new I/O), then calls `classify_chunk` to
//!    derive `(LexiconPlane, Option<LexiconVoice>)`, and writes the result
//!    back in-place.
//! 4. Bridge chunks that reach the retrieval layer have genuinely unknown
//!    provenance (e.g. inline runtime-generated text). The retrieval guard
//!    in `gaia-memos` treats Bridge as a pass-through.
//!
//! ## Signal priority (highest to lowest)
//!
//! 1. `attributes["sacred"] == "true"` → always `Chaos / Sacred`.
//! 2. Explicit attribute overrides: `attributes["human_authored"]`,
//!    `attributes["ai_generated"]`.
//! 3. `DocumentKind` inference (`CanonTablet`, `SpecDocument` → Order;
//!    `EpisodeSummary`, `SourceCode` → Order/AI; etc.).
//! 4. `provenance.source` (`DataSource`) inference.
//! 5. Language code — non-English raises Chaos probability for human-authored.
//! 6. Fallback → `Bridge`.
//!
//! Canon: C156 (KG + memory taxonomy), C30 (no silent failures)
//! DB mirror: supabase/migrations/20260923_gaia20_lexicon_order.sql
//!            supabase/migrations/20260923_gaia20_lexicon_chaos.sql

use serde::{Deserialize, Serialize};

use crate::document::{DocumentChunk, DocumentKind};
use crate::schema::DataSource;

// ── Plane ────────────────────────────────────────────────────────────────────

/// Which ontological plane this chunk's vocabulary belongs to.
///
/// - `Order`  — formal, machine-tractable, AI-authored or standards-body text.
/// - `Chaos`  — lived, cultural, human-authored, contested, or sacred text.
/// - `Bridge` — agreed interface points; safe default when provenance is unknown.
///
/// The chunker sets `Bridge` by default. `classify_document_chunk()` promotes
/// chunks to `Order` or `Chaos` based on document metadata. Promotion is
/// always explicit; the wall between planes is never crossed implicitly.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub enum LexiconPlane {
    Order,
    Chaos,
    Bridge,
}

impl Default for LexiconPlane {
    /// Safe default: `Bridge`.
    ///
    /// Unknown provenance must not be silently assigned to either plane.
    fn default() -> Self {
        Self::Bridge
    }
}

impl std::fmt::Display for LexiconPlane {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Order  => write!(f, "Order"),
            Self::Chaos  => write!(f, "Chaos"),
            Self::Bridge => write!(f, "Bridge"),
        }
    }
}

// ── Voice ────────────────────────────────────────────────────────────────────

/// Who speaks the vocabulary in this chunk.
///
/// Mirrors the `lexicon_voice` Postgres ENUM.
/// `None` is the safe default — voice is unknown until resolved.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub enum LexiconVoice {
    /// Authored by a person with lived experience.
    HumanVoice,
    /// Generated or defined by an AI system.
    AIVoice,
    /// Standards body, academic, or regulatory source.
    Institutional,
    /// TEK-gated community knowledge. Retrieval requires explicit grant.
    /// See `gaia-aikd/src/card.rs` `cannot_know()`.
    Sacred,
}

impl std::fmt::Display for LexiconVoice {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::HumanVoice    => write!(f, "HumanVoice"),
            Self::AIVoice       => write!(f, "AIVoice"),
            Self::Institutional => write!(f, "Institutional"),
            Self::Sacred        => write!(f, "Sacred"),
        }
    }
}

// ── LexiconSignals ────────────────────────────────────────────────────────────

/// Signals used by the ingestion pipeline to classify a chunk's lexicon plane.
///
/// These are derived from document-level metadata, not from the chunk text
/// itself. The chunker does not read content to classify — it reads provenance.
#[derive(Debug, Clone, Default)]
pub struct LexiconSignals {
    /// Source document was authored by a human (not AI-generated).
    pub human_authored: bool,
    /// Source document was generated by an AI system.
    pub ai_generated: bool,
    /// Standards body, academic, or regulatory source.
    pub institutional: bool,
    /// Language code (BCP-47). Non-English codes raise the probability of
    /// Chaos classification due to cultural embeddedness.
    pub language_code: Option<String>,
    /// Domain from `card.rs`. Some domains (e.g. `law`, `health`) have
    /// higher Chaos risk for human-authored content.
    pub domain: Option<String>,
    /// Explicit sacred/TEK flag from document metadata or consent record.
    pub sacred: bool,
}

// ── classify_chunk ────────────────────────────────────────────────────────────

/// Classify a chunk's lexicon plane from ingestion signals.
///
/// Rules (in priority order):
/// 1. Sacred flag → `Chaos / Sacred`.
/// 2. `human_authored` + non-English → `Chaos / HumanVoice`.
/// 3. `institutional` → `Order / Institutional`.
/// 4. `ai_generated` → `Order / AIVoice`.
/// 5. `human_authored` → `Chaos / HumanVoice`.
/// 6. Fallback → `Bridge / None`.
///
/// # Examples
///
/// ```rust
/// use gaia_ingest::lexicon::{classify_chunk, LexiconSignals, LexiconPlane, LexiconVoice};
///
/// let signals = LexiconSignals { ai_generated: true, ..Default::default() };
/// let (plane, voice) = classify_chunk(&signals);
/// assert_eq!(plane, LexiconPlane::Order);
/// assert_eq!(voice, Some(LexiconVoice::AIVoice));
/// ```
pub fn classify_chunk(signals: &LexiconSignals) -> (LexiconPlane, Option<LexiconVoice>) {
    if signals.sacred {
        return (LexiconPlane::Chaos, Some(LexiconVoice::Sacred));
    }

    let non_english = signals
        .language_code
        .as_deref()
        .map(|lc| !lc.starts_with("en"))
        .unwrap_or(false);

    if signals.human_authored && non_english {
        return (LexiconPlane::Chaos, Some(LexiconVoice::HumanVoice));
    }

    if signals.institutional {
        return (LexiconPlane::Order, Some(LexiconVoice::Institutional));
    }

    if signals.ai_generated {
        return (LexiconPlane::Order, Some(LexiconVoice::AIVoice));
    }

    if signals.human_authored {
        return (LexiconPlane::Chaos, Some(LexiconVoice::HumanVoice));
    }

    (LexiconPlane::Bridge, None)
}

// ── signals_from_chunk ────────────────────────────────────────────────────────

/// Derive `LexiconSignals` from the existing fields of a `DocumentChunk`.
///
/// Signal extraction follows a strict priority order — explicit `attributes`
/// override inferred `DataSource` / `DocumentKind` signals:
///
/// | Priority | Source | Signal |
/// |---|---|---|
/// | 1 (highest) | `attributes["sacred"] == "true"` | `sacred = true` |
/// | 2 | `attributes["human_authored"] == "true"` | `human_authored = true` |
/// | 2 | `attributes["ai_generated"] == "true"` | `ai_generated = true` |
/// | 3 | `DocumentKind` | see table below |
/// | 4 | `DataSource` | see table below |
/// | 5 (lowest) | `language` field | `language_code` |
///
/// ### DocumentKind → signals
///
/// | Kind | Signal |
/// |---|---|
/// | `CanonTablet` | `institutional = true` (sacred GAIA primary sources) |
/// | `SpecDocument` | `institutional = true` (authoritative spec) |
/// | `EpisodeSummary` | `ai_generated = true` (produced by `gaia-memos`) |
/// | `SourceCode` | `ai_generated = true` (machine-readable formal language) |
/// | `ResearchDocument` | no signal — defer to DataSource / attributes |
/// | `Other` | no signal — defer to DataSource / attributes |
///
/// ### DataSource → signals
///
/// | Source | Signal |
/// |---|---|
/// | `CanonTablet` | `institutional = true` |
/// | `SpecDocument` | `institutional = true` |
/// | `GbifOccurrence`, `GbifSpecies` | `institutional = true` (GBIF = standards body) |
/// | `Noaa`, `Copernicus`, `SentinelHub` | `institutional = true` (government/ESA) |
/// | `SensorThings` | `ai_generated = true` (machine sensor) |
/// | `ManualEntry` | `human_authored = true` |
/// | `ApiEndpoint` | `ai_generated = true` (machine-generated response) |
/// | others | no signal |
///
/// Attribute overrides (priority 2) always win over kind/source inference
/// (priorities 3–4), except `sacred` which is always highest priority.
pub fn signals_from_chunk(chunk: &DocumentChunk) -> LexiconSignals {
    let mut signals = LexiconSignals {
        language_code: Some(chunk.language.clone()),
        domain: Some(chunk.domain.clone()),
        ..Default::default()
    };

    // ── Priority 3: DocumentKind inference ──────────────────────────────────
    match chunk.kind {
        DocumentKind::CanonTablet | DocumentKind::SpecDocument => {
            signals.institutional = true;
        }
        DocumentKind::EpisodeSummary | DocumentKind::SourceCode => {
            signals.ai_generated = true;
        }
        DocumentKind::ResearchDocument | DocumentKind::Other => {
            // No kind-level signal; fall through to DataSource.
        }
    }

    // ── Priority 4: DataSource inference ────────────────────────────────────
    // Only apply if kind didn't already set a signal.
    if !signals.institutional && !signals.ai_generated && !signals.human_authored {
        match chunk.provenance.source {
            DataSource::CanonTablet | DataSource::SpecDocument => {
                signals.institutional = true;
            }
            DataSource::GbifOccurrence
            | DataSource::GbifSpecies
            | DataSource::Noaa
            | DataSource::Copernicus
            | DataSource::SentinelHub => {
                signals.institutional = true;
            }
            DataSource::SensorThings | DataSource::ApiEndpoint => {
                signals.ai_generated = true;
            }
            DataSource::ManualEntry => {
                signals.human_authored = true;
            }
            // OsmFeature, S3Artifact, Unknown — no signal; remain Bridge.
            _ => {}
        }
    }

    // ── Priority 2: Explicit attribute overrides ─────────────────────────────
    // These win over kind/source inference above.
    if chunk.attributes.get("human_authored").map(|v| v == "true").unwrap_or(false) {
        signals.ai_generated    = false;
        signals.institutional   = false;
        signals.human_authored  = true;
    }
    if chunk.attributes.get("ai_generated").map(|v| v == "true").unwrap_or(false) {
        signals.human_authored  = false;
        signals.institutional   = false;
        signals.ai_generated    = true;
    }

    // ── Priority 1: Sacred flag ──────────────────────────────────────────────
    // Wins over everything — set last so nothing above can clear it.
    if chunk.attributes.get("sacred").map(|v| v == "true").unwrap_or(false) {
        signals.sacred = true;
    }

    signals
}

// ── classify_document_chunk ──────────────────────────────────────────────────

/// Classify `chunk.lexicon_plane` and `chunk.lexicon_voice` in-place.
///
/// This is the **single call-site** the ingestion pipeline must use after
/// chunking. It derives signals from the chunk's existing provenance fields
/// via `signals_from_chunk()`, runs `classify_chunk()`, and writes the result
/// back.
///
/// ## Idempotency
///
/// If `chunk.lexicon_plane != Bridge` this function is a no-op — the chunk
/// was already classified (e.g. by a prior pipeline stage or an explicit
/// override) and must not be silently re-classified.
///
/// ## Usage
///
/// ```rust,ignore
/// use gaia_ingest::lexicon::classify_document_chunk;
///
/// for chunk in chunker.chunks_mut() {
///     classify_document_chunk(chunk);
/// }
/// ```
pub fn classify_document_chunk(chunk: &mut DocumentChunk) {
    // Idempotency guard: don't overwrite an explicit classification.
    if chunk.lexicon_plane != LexiconPlane::Bridge {
        return;
    }

    let signals = signals_from_chunk(chunk);
    let (plane, voice) = classify_chunk(&signals);

    chunk.lexicon_plane = plane;
    // Only write voice if classification resolved it — preserve None for
    // genuine Bridge chunks where voice is also unknown.
    if voice.is_some() {
        chunk.lexicon_voice = voice;
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{
        document::{AccessTier, ConfidenceTier, DocumentChunk, DocumentKind},
        provenance::ProvenanceReceipt,
        schema::DataSource,
    };
    use std::collections::BTreeMap;

    // ── classify_chunk (existing) ────────────────────────────────────────────

    #[test]
    fn default_plane_is_bridge() {
        assert_eq!(LexiconPlane::default(), LexiconPlane::Bridge);
    }

    #[test]
    fn sacred_always_chaos() {
        let signals = LexiconSignals { sacred: true, ..Default::default() };
        let (plane, voice) = classify_chunk(&signals);
        assert_eq!(plane, LexiconPlane::Chaos);
        assert_eq!(voice, Some(LexiconVoice::Sacred));
    }

    #[test]
    fn ai_generated_is_order() {
        let signals = LexiconSignals { ai_generated: true, ..Default::default() };
        let (plane, voice) = classify_chunk(&signals);
        assert_eq!(plane, LexiconPlane::Order);
        assert_eq!(voice, Some(LexiconVoice::AIVoice));
    }

    #[test]
    fn institutional_is_order() {
        let signals = LexiconSignals { institutional: true, ..Default::default() };
        let (plane, voice) = classify_chunk(&signals);
        assert_eq!(plane, LexiconPlane::Order);
        assert_eq!(voice, Some(LexiconVoice::Institutional));
    }

    #[test]
    fn human_authored_english_is_chaos() {
        let signals = LexiconSignals {
            human_authored: true,
            language_code: Some("en".into()),
            ..Default::default()
        };
        let (plane, voice) = classify_chunk(&signals);
        assert_eq!(plane, LexiconPlane::Chaos);
        assert_eq!(voice, Some(LexiconVoice::HumanVoice));
    }

    #[test]
    fn human_authored_non_english_is_chaos() {
        let signals = LexiconSignals {
            human_authored: true,
            language_code: Some("mi".into()),  // Māori
            ..Default::default()
        };
        let (plane, voice) = classify_chunk(&signals);
        assert_eq!(plane, LexiconPlane::Chaos);
        assert_eq!(voice, Some(LexiconVoice::HumanVoice));
    }

    #[test]
    fn unknown_provenance_is_bridge() {
        let signals = LexiconSignals::default();
        let (plane, voice) = classify_chunk(&signals);
        assert_eq!(plane, LexiconPlane::Bridge);
        assert_eq!(voice, None);
    }

    #[test]
    fn sacred_overrides_ai_generated() {
        let signals = LexiconSignals {
            sacred: true,
            ai_generated: true,
            ..Default::default()
        };
        let (plane, voice) = classify_chunk(&signals);
        assert_eq!(plane, LexiconPlane::Chaos);
        assert_eq!(voice, Some(LexiconVoice::Sacred));
    }

    #[test]
    fn display_round_trip() {
        assert_eq!(LexiconPlane::Order.to_string(),  "Order");
        assert_eq!(LexiconPlane::Chaos.to_string(),  "Chaos");
        assert_eq!(LexiconPlane::Bridge.to_string(), "Bridge");
        assert_eq!(LexiconVoice::HumanVoice.to_string(),    "HumanVoice");
        assert_eq!(LexiconVoice::AIVoice.to_string(),       "AIVoice");
        assert_eq!(LexiconVoice::Institutional.to_string(), "Institutional");
        assert_eq!(LexiconVoice::Sacred.to_string(),        "Sacred");
    }

    // ── signals_from_chunk ───────────────────────────────────────────────────

    fn base_chunk(kind: DocumentKind, source: DataSource) -> DocumentChunk {
        let text = "test chunk text for classification".to_string();
        let char_count = text.chars().count();
        DocumentChunk {
            id:               "00000000-0000-0000-0000-000000000001".into(),
            document_title:   "Test Document".into(),
            document_uri:     "gaia://test/doc".into(),
            kind,
            char_count,
            text,
            chunk_index:      0,
            total_chunks:     1,
            domain:           "test".into(),
            language:         "en".into(),
            authored_at_unix: None,
            ttl_seconds:      None,
            confidence:       ConfidenceTier::Verified,
            access_tier:      AccessTier::Public,
            access_control:   vec![],
            provenance: ProvenanceReceipt {
                source,
                source_url:       "gaia://test/doc".into(),
                external_id:      "test-001".into(),
                fetched_at_unix:  1_700_000_001,
                observed_at_unix: 1_700_000_000,
                sha256:           "a".repeat(64),
                license:          "CC-BY-4.0".into(),
            },
            artifact:        None,
            attributes:      BTreeMap::new(),
            lexicon_plane:   LexiconPlane::Bridge,
            lexicon_voice:   None,
        }
    }

    #[test]
    fn signals_canon_tablet_is_order_institutional() {
        let chunk = base_chunk(DocumentKind::CanonTablet, DataSource::CanonTablet);
        let s = signals_from_chunk(&chunk);
        assert!(s.institutional);
        assert!(!s.ai_generated);
        assert!(!s.human_authored);
        assert!(!s.sacred);
    }

    #[test]
    fn signals_spec_document_is_order_institutional() {
        let chunk = base_chunk(DocumentKind::SpecDocument, DataSource::SpecDocument);
        let s = signals_from_chunk(&chunk);
        assert!(s.institutional);
        assert!(!s.ai_generated);
    }

    #[test]
    fn signals_episode_summary_is_order_ai() {
        let chunk = base_chunk(DocumentKind::EpisodeSummary, DataSource::ApiEndpoint);
        let s = signals_from_chunk(&chunk);
        assert!(s.ai_generated);
        assert!(!s.institutional);
    }

    #[test]
    fn signals_source_code_is_order_ai() {
        let chunk = base_chunk(DocumentKind::SourceCode, DataSource::ApiEndpoint);
        let s = signals_from_chunk(&chunk);
        assert!(s.ai_generated);
    }

    #[test]
    fn signals_non_english_human_authored_attr() {
        let mut chunk = base_chunk(DocumentKind::Other, DataSource::ManualEntry);
        chunk.language = "mi".into();  // Māori
        let s = signals_from_chunk(&chunk);
        assert!(s.human_authored);
        assert_eq!(s.language_code.as_deref(), Some("mi"));
    }

    #[test]
    fn signals_sacred_attribute_wins() {
        // Even a CanonTablet (institutional) becomes sacred if the attribute is set.
        let mut chunk = base_chunk(DocumentKind::CanonTablet, DataSource::CanonTablet);
        chunk.attributes.insert("sacred".into(), "true".into());
        let s = signals_from_chunk(&chunk);
        assert!(s.sacred);
        // institutional is still set from kind, but sacred wins in classify_chunk()
        assert!(s.institutional);
    }

    #[test]
    fn signals_attribute_overrides_datasource() {
        // DataSource::Noaa would set institutional, but explicit attribute wins.
        let mut chunk = base_chunk(DocumentKind::Other, DataSource::Noaa);
        chunk.attributes.insert("human_authored".into(), "true".into());
        let s = signals_from_chunk(&chunk);
        // attribute override clears institutional, sets human_authored
        assert!(s.human_authored);
        assert!(!s.institutional);
    }

    // ── classify_document_chunk ──────────────────────────────────────────────

    #[test]
    fn classify_doc_chunk_promotes_bridge_canon_tablet() {
        let mut chunk = base_chunk(DocumentKind::CanonTablet, DataSource::CanonTablet);
        assert_eq!(chunk.lexicon_plane, LexiconPlane::Bridge);
        classify_document_chunk(&mut chunk);
        assert_eq!(chunk.lexicon_plane, LexiconPlane::Order);
        assert_eq!(chunk.lexicon_voice, Some(LexiconVoice::Institutional));
    }

    #[test]
    fn classify_doc_chunk_skips_already_classified() {
        let mut chunk = base_chunk(DocumentKind::CanonTablet, DataSource::CanonTablet);
        // Manually pre-classify as Chaos.
        chunk.lexicon_plane = LexiconPlane::Chaos;
        chunk.lexicon_voice = Some(LexiconVoice::HumanVoice);
        classify_document_chunk(&mut chunk);
        // Must not be overwritten.
        assert_eq!(chunk.lexicon_plane, LexiconPlane::Chaos);
        assert_eq!(chunk.lexicon_voice, Some(LexiconVoice::HumanVoice));
    }

    #[test]
    fn classify_doc_chunk_chaos_from_human_authored_attr() {
        let mut chunk = base_chunk(DocumentKind::ResearchDocument, DataSource::ManualEntry);
        chunk.attributes.insert("human_authored".into(), "true".into());
        classify_document_chunk(&mut chunk);
        assert_eq!(chunk.lexicon_plane, LexiconPlane::Chaos);
        assert_eq!(chunk.lexicon_voice, Some(LexiconVoice::HumanVoice));
    }

    #[test]
    fn classify_doc_chunk_sacred_attr() {
        let mut chunk = base_chunk(DocumentKind::Other, DataSource::ManualEntry);
        chunk.attributes.insert("sacred".into(), "true".into());
        classify_document_chunk(&mut chunk);
        assert_eq!(chunk.lexicon_plane, LexiconPlane::Chaos);
        assert_eq!(chunk.lexicon_voice, Some(LexiconVoice::Sacred));
    }

    #[test]
    fn classify_doc_chunk_idempotent_order() {
        let mut chunk = base_chunk(DocumentKind::CanonTablet, DataSource::CanonTablet);
        classify_document_chunk(&mut chunk);
        let plane_after_first = chunk.lexicon_plane;
        let voice_after_first = chunk.lexicon_voice.clone();
        classify_document_chunk(&mut chunk);
        assert_eq!(chunk.lexicon_plane, plane_after_first);
        assert_eq!(chunk.lexicon_voice, voice_after_first);
    }

    #[test]
    fn classify_doc_chunk_episode_summary_is_order_ai() {
        let mut chunk = base_chunk(DocumentKind::EpisodeSummary, DataSource::ApiEndpoint);
        classify_document_chunk(&mut chunk);
        assert_eq!(chunk.lexicon_plane, LexiconPlane::Order);
        assert_eq!(chunk.lexicon_voice, Some(LexiconVoice::AIVoice));
    }

    #[test]
    fn classify_doc_chunk_noaa_research_is_order_institutional() {
        // ResearchDocument from NOAA → institutional via DataSource.
        let mut chunk = base_chunk(DocumentKind::ResearchDocument, DataSource::Noaa);
        classify_document_chunk(&mut chunk);
        assert_eq!(chunk.lexicon_plane, LexiconPlane::Order);
        assert_eq!(chunk.lexicon_voice, Some(LexiconVoice::Institutional));
    }

    #[test]
    fn classify_doc_chunk_unknown_source_stays_bridge() {
        // Other kind + Unknown source + no attributes → stays Bridge.
        let mut chunk = base_chunk(DocumentKind::Other, DataSource::Unknown);
        classify_document_chunk(&mut chunk);
        assert_eq!(chunk.lexicon_plane, LexiconPlane::Bridge);
        assert_eq!(chunk.lexicon_voice, None);
    }
}
