//! Lexicon plane classification for GAIA-2.0 document chunks.
//!
//! Two parallel dictionaries — Order and Chaos — must never be silently conflated.
//! Every `DocumentChunk` emitted by the chunker carries a `LexiconPlane` tag so
//! the RAG pipeline always knows which plane it is pulling from.
//!
//! Canon: C156 (KG + memory taxonomy), C30 (no silent failures)
//! DB mirror: supabase/migrations/20260923_gaia20_lexicon_order.sql
//!            supabase/migrations/20260923_gaia20_lexicon_chaos.sql

use serde::{Deserialize, Serialize};

// ── Plane ────────────────────────────────────────────────────────────────────

/// Which ontological plane this chunk's vocabulary belongs to.
///
/// - `Order`  — formal, machine-tractable, AI-authored or standards-body text.
/// - `Chaos`  — lived, cultural, human-authored, contested, or sacred text.
/// - `Bridge` — agreed interface points; safe default when provenance is unknown.
///
/// The chunker sets `Bridge` by default. A downstream pipeline step promotes
/// chunks to `Order` or `Chaos` based on document metadata (author type,
/// source registry, language, domain). Promotion is always explicit; the wall
/// between planes is never crossed implicitly.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub enum LexiconPlane {
    Order,
    Chaos,
    Bridge,
}

impl Default for LexiconPlane {
    /// Safe default: `Bridge`.
    ///
    /// Unknown provenance must not be silently assigned to either plane.
    /// The RAG pipeline treats Bridge chunks as requiring explicit plane
    /// resolution before cross-plane retrieval.
    fn default() -> Self {
        Self::Bridge
    }
}

impl std::fmt::Display for LexiconPlane {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Order  => write!(f, "Order"),
            Self::Chaos  => write!(f, "Chaos"),
            Self::Bridge => write!(f, "Bridge"),
        }
    }
}

// ── Voice ────────────────────────────────────────────────────────────────────

/// Who speaks the vocabulary in this chunk.
///
/// Mirrors the `lexicon_voice` Postgres ENUM.
/// `None` is the safe default — voice is unknown until resolved.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub enum LexiconVoice {
    /// Authored by a person with lived experience.
    HumanVoice,
    /// Generated or defined by an AI system.
    AIVoice,
    /// Standards body, academic, or regulatory source.
    Institutional,
    /// TEK-gated community knowledge. Retrieval requires explicit grant.
    /// See `gaia-aikd/src/card.rs` `cannot_know()`.
    Sacred,
}

impl std::fmt::Display for LexiconVoice {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::HumanVoice    => write!(f, "HumanVoice"),
            Self::AIVoice       => write!(f, "AIVoice"),
            Self::Institutional => write!(f, "Institutional"),
            Self::Sacred        => write!(f, "Sacred"),
        }
    }
}

// ── Classification helper ────────────────────────────────────────────────────

/// Signals used by the ingestion pipeline to classify a chunk's lexicon plane.
///
/// These are derived from document-level metadata, not from the chunk text
/// itself. The chunker does not read content to classify — it reads provenance.
#[derive(Debug, Clone, Default)]
pub struct LexiconSignals {
    /// Source document was authored by a human (not AI-generated).
    pub human_authored: bool,
    /// Source document was generated by an AI system.
    pub ai_generated: bool,
    /// Language code (BCP-47). Non-English codes raise the probability of
    /// Chaos classification due to cultural embeddedness.
    pub language_code: Option<String>,
    /// Domain from `card.rs`. Some domains (e.g. `law`, `health`) have
    /// higher Chaos risk for human-authored content.
    pub domain: Option<String>,
    /// Explicit sacred/TEK flag from document metadata or consent record.
    pub sacred: bool,
}

/// Classify a chunk's lexicon plane from ingestion signals.
///
/// Rules (in priority order):
/// 1. Sacred flag → `Chaos` (TEK is always on the human plane).
/// 2. `human_authored` + non-English → `Chaos` (language carries culture).
/// 3. `ai_generated` → `Order`.
/// 4. `human_authored` → `Chaos`.
/// 5. Fallback → `Bridge`.
///
/// The voice is derived from the same signals.
///
/// # Examples
///
/// ```rust
/// use gaia_ingest::lexicon::{classify_chunk, LexiconSignals, LexiconPlane, LexiconVoice};
///
/// let signals = LexiconSignals { ai_generated: true, ..Default::default() };
/// let (plane, voice) = classify_chunk(&signals);
/// assert_eq!(plane, LexiconPlane::Order);
/// assert_eq!(voice, Some(LexiconVoice::AIVoice));
/// ```
pub fn classify_chunk(signals: &LexiconSignals) -> (LexiconPlane, Option<LexiconVoice>) {
    if signals.sacred {
        return (LexiconPlane::Chaos, Some(LexiconVoice::Sacred));
    }

    let non_english = signals
        .language_code
        .as_deref()
        .map(|lc| !lc.starts_with("en"))
        .unwrap_or(false);

    if signals.human_authored && non_english {
        return (LexiconPlane::Chaos, Some(LexiconVoice::HumanVoice));
    }

    if signals.ai_generated {
        return (LexiconPlane::Order, Some(LexiconVoice::AIVoice));
    }

    if signals.human_authored {
        return (LexiconPlane::Chaos, Some(LexiconVoice::HumanVoice));
    }

    (LexiconPlane::Bridge, None)
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_plane_is_bridge() {
        assert_eq!(LexiconPlane::default(), LexiconPlane::Bridge);
    }

    #[test]
    fn sacred_always_chaos() {
        let signals = LexiconSignals { sacred: true, ..Default::default() };
        let (plane, voice) = classify_chunk(&signals);
        assert_eq!(plane, LexiconPlane::Chaos);
        assert_eq!(voice, Some(LexiconVoice::Sacred));
    }

    #[test]
    fn ai_generated_is_order() {
        let signals = LexiconSignals { ai_generated: true, ..Default::default() };
        let (plane, voice) = classify_chunk(&signals);
        assert_eq!(plane, LexiconPlane::Order);
        assert_eq!(voice, Some(LexiconVoice::AIVoice));
    }

    #[test]
    fn human_authored_english_is_chaos() {
        let signals = LexiconSignals {
            human_authored: true,
            language_code: Some("en".into()),
            ..Default::default()
        };
        let (plane, voice) = classify_chunk(&signals);
        assert_eq!(plane, LexiconPlane::Chaos);
        assert_eq!(voice, Some(LexiconVoice::HumanVoice));
    }

    #[test]
    fn human_authored_non_english_is_chaos() {
        let signals = LexiconSignals {
            human_authored: true,
            language_code: Some("mi".into()),  // Māori
            ..Default::default()
        };
        let (plane, voice) = classify_chunk(&signals);
        assert_eq!(plane, LexiconPlane::Chaos);
        assert_eq!(voice, Some(LexiconVoice::HumanVoice));
    }

    #[test]
    fn unknown_provenance_is_bridge() {
        let signals = LexiconSignals::default();
        let (plane, voice) = classify_chunk(&signals);
        assert_eq!(plane, LexiconPlane::Bridge);
        assert_eq!(voice, None);
    }

    #[test]
    fn sacred_overrides_ai_generated() {
        // If somehow both flags are set, sacred wins — TEK is never Order.
        let signals = LexiconSignals {
            sacred: true,
            ai_generated: true,
            ..Default::default()
        };
        let (plane, voice) = classify_chunk(&signals);
        assert_eq!(plane, LexiconPlane::Chaos);
        assert_eq!(voice, Some(LexiconVoice::Sacred));
    }

    #[test]
    fn display_round_trip() {
        assert_eq!(LexiconPlane::Order.to_string(),  "Order");
        assert_eq!(LexiconPlane::Chaos.to_string(),  "Chaos");
        assert_eq!(LexiconPlane::Bridge.to_string(), "Bridge");
        assert_eq!(LexiconVoice::HumanVoice.to_string(),    "HumanVoice");
        assert_eq!(LexiconVoice::AIVoice.to_string(),       "AIVoice");
        assert_eq!(LexiconVoice::Institutional.to_string(), "Institutional");
        assert_eq!(LexiconVoice::Sacred.to_string(),        "Sacred");
    }
}
