//! Adversarial test: Deepfake Illusionist — ClaimClass::Synthetic presentation (#958).
//!
//! Forbidden-role bind: docs/agents/FORBIDDEN-ROLE-TEST-BIND.md
//! Canon: C30, moral-architecture P5 (transformation without violating consent)
//! Parent epic: #901

use gaia_acp::*;

#[test]
fn synthetic_claim_without_disclosure_is_rejected() {
    let claim = Claim {
        class: ClaimClass::Synthetic,
        content: "This image is a real photograph.".into(),
        synthetic_disclosed: false,
        provenance: Some("generator-v1".into()),
    };
    assert_eq!(
        claim_gate(&claim),
        Err(ReasonCode::SyntheticDisclosureRequired),
        "a synthetic claim without disclosure must be rejected"
    );
}

#[test]
fn synthetic_claim_with_disclosure_passes() {
    let claim = Claim {
        class: ClaimClass::Synthetic,
        content: "This image was generated by model-v1 (synthetic).".into(),
        synthetic_disclosed: true,
        provenance: Some("generator-v1".into()),
    };
    assert!(claim_gate(&claim).is_ok());
}

#[test]
fn non_synthetic_claim_is_not_affected() {
    let claim = Claim {
        class: ClaimClass::Observed,
        content: "The sensor reading was 42.0.".into(),
        synthetic_disclosed: false,
        provenance: Some("sensor-abc".into()),
    };
    assert!(claim_gate(&claim).is_ok());
}

#[test]
fn synthetic_claim_no_provenance_no_disclosure_is_rejected() {
    let claim = Claim {
        class: ClaimClass::Synthetic,
        content: "Definitely real footage.".into(),
        synthetic_disclosed: false,
        provenance: None,
    };
    assert_eq!(
        claim_gate(&claim),
        Err(ReasonCode::SyntheticDisclosureRequired)
    );
}
