//! Adversarial test: Deepfake Illusionist — ClaimClass::Synthetic presentation (#958).
//!
//! Forbidden-role bind: docs/agents/FORBIDDEN-ROLE-TEST-BIND.md
//! Canon: C30, moral-architecture P5 (transformation without violating consent)
//! Parent epic: #901
//!
//! A deepfake illusionist presents synthetic content without disclosing its
//! synthetic origin. Any `ClaimClass::Synthetic` claim that lacks the
//! `synthetic_disclosed: true` flag must be rejected at the ACP claim gate.

use gaia_acp::*;

/// A synthetic claim with disclosure suppressed must be rejected.
#[test]
fn synthetic_claim_without_disclosure_is_rejected() {
    let claim = Claim {
        class: ClaimClass::Synthetic,
        content: "This image is a real photograph.".into(),
        synthetic_disclosed: false, // deepfake suppression
        provenance: Some("generator-v1".into()),
    };
    assert_eq!(
        claim_gate(&claim),
        Err(ReasonCode::SyntheticDisclosureRequired),
        "a synthetic claim without disclosure must be rejected"
    );
}

/// A synthetic claim with disclosure present must pass.
#[test]
fn synthetic_claim_with_disclosure_passes() {
    let claim = Claim {
        class: ClaimClass::Synthetic,
        content: "This image was generated by model-v1 (synthetic).".into(),
        synthetic_disclosed: true,
        provenance: Some("generator-v1".into()),
    };
    assert!(
        claim_gate(&claim).is_ok(),
        "a synthetic claim with disclosure must pass the claim gate"
    );
}

/// A non-synthetic claim is unaffected by the synthetic disclosure rule.
#[test]
fn non_synthetic_claim_is_not_affected() {
    let claim = Claim {
        class: ClaimClass::Observed,
        content: "The sensor reading was 42.0.".into(),
        synthetic_disclosed: false, // irrelevant for Observed
        provenance: Some("sensor-abc".into()),
    };
    assert!(
        claim_gate(&claim).is_ok(),
        "a non-synthetic observed claim must pass regardless of synthetic_disclosed flag"
    );
}

/// A synthetic claim with no provenance at all is doubly rejected — disclosure gap + missing provenance.
#[test]
fn synthetic_claim_no_provenance_no_disclosure_is_rejected() {
    let claim = Claim {
        class: ClaimClass::Synthetic,
        content: "Definitely real footage.".into(),
        synthetic_disclosed: false,
        provenance: None,
    };
    assert_eq!(
        claim_gate(&claim),
        Err(ReasonCode::SyntheticDisclosureRequired),
        "synthetic claim missing both disclosure and provenance must be hard-rejected"
    );
}
